_wandb:
    value:
        cli_version: 0.22.0
        e:
            e0qrmu4yu2170kwccp2rd6rg8hla56sq:
                cpu_count: 10
                cpu_count_logical: 16
                disk:
                    /:
                        total: "499462959104"
                        used: "401105092608"
                email: rmsh@umich.edu
                executable: C:\Users\User\anaconda3\python.exe
                git:
                    commit: 6eaf8afd1688063d9ab0d76604874d33086ea217
                    remote: git@github.com:rameshrahul/595_projects.git
                host: DESKTOP-AV00LQI
                memory:
                    total: "34122387456"
                os: Windows-10-10.0.19045-SP0
                program: Documents/Projects/595_projects/HW2/Word2Vec Pytorch Student.ipynb
                python: CPython 3.12.7
                root: C:\Users\User\Documents\Projects\595_projects\HW2
                startedAt: "2025-10-08T23:39:32.677842Z"
                writerId: e0qrmu4yu2170kwccp2rd6rg8hla56sq
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.12.7
            "5": 0.22.0
            "8":
                - 1
                - 3
            "12": 0.22.0
            "13": windows-amd64
batch_size:
    value: 1024
epochs:
    value: 1
